name: Build uv cache

on:
  push:
    branches:
      - main
    paths:
      - "uv.lock"
      - "pyproject.toml"
  workflow_dispatch:

jobs:
  build-cache:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.22"
          enable-cache: false

     
      - name: Install dependencies and populate cache
        run: |
          echo "add ruff"
          uv add --dev ruff
          echo "Building global UV cache..."
          uv sync --group dev
          echo "Cache populated successfully"

      - name: Save uv caches
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cache/uv
            ~/.local/share/uv
            .venv
          key: uv-main-${{ hashFiles('uv.lock') }}